version: '3'
services:
  db:
    image: mysql:5.7
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lb/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=links
      - MYSQL_USER=measmyself
      - MYSQL_PASSWORD=secret
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
  app:
    build: .
    networks:
      - mynetwork
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file:
      - .env
    ports:
      - 3015:3015
    environment:
      - JWT_SECRET=secret
    depends_on:
      - db
volumes:
  db_data:

networks:
  mynetwork:
    external: true
