export const DATA_SOURCE = 'DATA_SOURCE';
export const PAGE_REPOSITORY = 'PAGE_REPOSITORY';
export const LINK_REPOSITORY = 'LINK_REPOSITORY';
export const LINK_CLICK_REPOSITORY = 'LINK_CLICK_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
